logger:
  level: info
  output_paths:
    - stdout

discord:
  guild_id: "836026401823260733"
  command_channel: "1326784974602637413"
  report_channel: "1326784974602637413"

raiderio:
  base_url: https://raider.io
  user_agent: celestial-orrey/1.0
  poll_interval: 5m
  max_concurrent: 4

store:
  path: data/celestial_orrey.db

warcraftlogs:
  guild_name: ""
  server_slug: ""
  server_region: ""
  limit: 50

characters:
  - name: Askr
    realm: Mal'Ganis
    region: us
  - name: Askrm
    realm: Mal'Ganis
    region: us
