logger:
  level: debug
  output_paths:
    - stdout

discord:
  guild_id: "836026401823260733"
  listen_channel: "1326784974602637413"

raiderio:
  base_url: https://raider.io
  user_agent: celestial-orrey/1.0
  poll_interval: 1m
  max_concurrent: 10

store:
  path: data/celestial_orrey.db
  backup_dir: data/backup
